# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is NOT generated by device/motorola/mods/setup-makefiles.sh

ifeq ($(strip $(USE_MOTO_AUDIOHAL)),true)
PRODUCT_COPY_FILES += \
    vendor/motorola/mods/proprietary/vendor/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/motorola/mods/proprietary/vendor/lib/libtinyalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtinyalsa.so \
    vendor/motorola/mods/proprietary/vendor/lib/libmotaudioutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmotaudioutils.so \
    vendor/motorola/mods/proprietary/vendor/lib/libunshorten.so:$(TARGET_COPY_OUT_VENDOR)/lib/libunshorten.so \
    vendor/motorola/mods/proprietary/vendor/lib/hw/audio.primary.qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.qcom.so
endif

ifeq ($(strip $(USE_MOTO_HEALTHHAL)),true)
PRODUCT_COPY_FILES += \
    vendor/motorola/mods/proprietary/vendor/etc/init/motorola.hardware.health@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.health@1.0-service.rc \
    vendor/motorola/mods/proprietary/vendor/bin/hw/motorola.hardware.health@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.health@1.0-service \
    vendor/motorola/mods/proprietary/vendor/lib64/motorola.hardware.health@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.health@1.0.so
endif
